server:
  port: 0

spring:
  application:
    name: user-service

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true # eureka ????? ?????? ??? ????? ??? ??? ???? ??. ture=??? ??? ???? ???.
    service-url:
      defaultZone: http://192.168.1.100:8761/eureka # service-url.defaultZone :: ??? ?? URL